version: '3'

services:
  db:
    image: trieuvu/db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: tlcn
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
#    deploy:
#      resources:
#        limits:
#          cpus: '0.2'
#          memory: 200M
#        reservations:
#          cpus: '0.1'
#          memory: 100M

  be:
    image: trieuvu/tlcn-be
    environment:
      - APP_DB_URL=jdbc:mysql://db:3306/tlcn
      - APP_DB_USERNAME=root
      - APP_DB_PASSWORD=12345
    ports:
      - 8001:8001
      - 8443:8443
    depends_on:
      - db
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 200M
#        reservations:
#          cpus: '0.25'
#          memory: 100M
