spring:
  application:
    name: tlcn
  datasource:
    url: ${APP_DB_URL:jdbc:mysql://localhost:3306/tlcn}
    username: ${APP_DB_USERNAME:root}
    password: ${APP_DB_PASSWORD:12345}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${APP_MAIL_USER:username@gmail.com}
    password: ${APP_MAIL_PASS:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
server:
  port: 8443
  ssl:
    key-store: ${APP_KEYSTORE:classpath:keystore.p12}
    key-store-password: ${APP_KEYSTORE_PASS:password}
    keyStoreType: PKCS12
    keyAlias: tomcat
  http:
    port: 8001

myapp:
  security:
    jwt:
      secret: bXlfc2VjcmV0X2tleQ==
      expiration: 86400000 #3600000 # 1 hour
  url:
    recommend: ${APP_URL_RECOMMEND:http://localhost:5000}
    path-recommend-user: /recommend/user/
    path-recommend-product: /recommend/product/

