spring:
  application:
    name: tlcn
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kltn
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  web:
    resources:
      static-locations: file:/static

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${APP_MAIL_USER:username@gmail.com}
    password: ${APP_MAIL_PASS:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: p@ssw0rd
    keyStoreType: PKCS12
    keyAlias: tomcat
  http:
    port: 8001
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

myapp:
  security:
    jwt:
      secret: bXlfc2VjcmV0X2tleQ==
      expiration: 86400000 #3600000 # 1 hour
  url:
    recommend: ${APP_URL_RECOMMEND:http://localhost:5000}
    predict: ${APP_URL_PREDICT:http://localhost:5001}
    path-recommend-user: /recommend/user/
    path-recommend-product: /recommend/product/
ghn:
  token: ${GHN_TOKEN:token}
  shop-id: ${GHN_SHOP_ID:123456}
  url: ${GHN_URL:https://dev-online-gateway.ghn.vn/shiip/public-api}
