spring:
  application:
    name: tlcn
  datasource:
    url: ${APP_DB_URL:jdbc:mysql://localhost:3306/tlcn}
    username: ${APP_DB_USERNAME:root}
    password: ${APP_DB_PASSWORD:12345}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: shop.vuductrieu@gmail.com
    password: majfygbwgunueusw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8001

myapp:
  security:
    jwt:
      secret: bXlfc2VjcmV0X2tleQ==
      expiration: 86400000 #3600000 # 1 hour


